// Code generated by tools/gen_blocks.go. DO NOT EDIT.
package registry

// MinecraftVersion is the Minecraft version this registry was generated from.
const MinecraftVersion = "1.21.4"

// PropertyDef describes a block property's valid values and default.
type PropertyDef struct {
	Values  []string
	Default string
}

// BlockProperties maps block names to their property definitions.
var BlockProperties = map[string]map[string]PropertyDef{
	"minecraft:air": {},
}

// AllBlocks is a list of all known block names.
var AllBlocks = []string{
	"minecraft:air",
}
