// tools/gen_blocks.go generates Go source code from Minecraft's blocks.json report.
//
// Usage:
//
//	go run tools/gen_blocks.go data/blocks.json > pkg/registry/blocks_generated.go
//
// blocks.json is extracted from the vanilla server jar via:
//
//	java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// BlockReport is the structure of Minecraft's generated blocks.json
type BlockReport struct {
	// key = "minecraft:stone", etc.
}

type BlockDefinition struct {
	Properties map[string][]string `json:"properties"`
	States     []BlockStateEntry   `json:"states"`
}

type BlockStateEntry struct {
	ID         int               `json:"id"`
	Default    bool              `json:"default"`
	Properties map[string]string `json:"properties"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: gen_blocks <blocks.json>\n")
		os.Exit(1)
	}

	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to open %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}
	defer f.Close()

	var blocks map[string]BlockDefinition
	if err := json.NewDecoder(f).Decode(&blocks); err != nil {
		fmt.Fprintf(os.Stderr, "failed to decode blocks.json: %v\n", err)
		os.Exit(1)
	}

	// Determine version from filename hint or environment
	version := os.Getenv("MC_VERSION")
	if version == "" {
		version = "unknown"
	}

	// Sort block names for deterministic output
	blockNames := make([]string, 0, len(blocks))
	for name := range blocks {
		blockNames = append(blockNames, name)
	}
	sort.Strings(blockNames)

	fmt.Println("// Code generated by tools/gen_blocks.go. DO NOT EDIT.")
	fmt.Println("package registry")
	fmt.Println()
	fmt.Printf("// MinecraftVersion is the Minecraft version this registry was generated from.\n")
	fmt.Printf("const MinecraftVersion = %q\n\n", version)

	fmt.Println("// PropertyDef describes a block property's valid values and default.")
	fmt.Println("type PropertyDef struct {")
	fmt.Println("\tValues  []string")
	fmt.Println("\tDefault string")
	fmt.Println("}")
	fmt.Println()

	fmt.Println("// BlockProperties maps block names to their property definitions.")
	fmt.Println("var BlockProperties = map[string]map[string]PropertyDef{")

	for _, name := range blockNames {
		def := blocks[name]
		if len(def.Properties) == 0 {
			continue // Skip blocks with no properties
		}

		// Find default state
		defaults := make(map[string]string)
		for _, state := range def.States {
			if state.Default {
				defaults = state.Properties
				break
			}
		}

		// Sort property names
		propNames := make([]string, 0, len(def.Properties))
		for pn := range def.Properties {
			propNames = append(propNames, pn)
		}
		sort.Strings(propNames)

		fmt.Printf("\t%q: {\n", name)
		for _, pn := range propNames {
			vals := def.Properties[pn]
			defVal := defaults[pn]
			quotedVals := make([]string, len(vals))
			for i, v := range vals {
				quotedVals[i] = fmt.Sprintf("%q", v)
			}
			fmt.Printf("\t\t%q: {Values: []string{%s}, Default: %q},\n",
				pn, strings.Join(quotedVals, ", "), defVal)
		}
		fmt.Println("\t},")
	}

	fmt.Println("}")

	// Also generate a simple block list
	fmt.Println()
	fmt.Println("// AllBlocks is a list of all known block names.")
	fmt.Println("var AllBlocks = []string{")
	for _, name := range blockNames {
		fmt.Printf("\t%q,\n", name)
	}
	fmt.Println("}")
}
